### ISSUE TITLE
Small typo in "jak-na-konflikty.md"

### ISSUE THREAD

**Issue by ryzzaki** [Applifting/culture#16]
> "Vypadá to, že se nám samotným nedaří **shonout** na dalším postupu. Kdo by nám mohl pomoci najít řešení? Komu oba dva důvěřujeme?"

The small typo is found in the following word:
`shonout => sho**d**nout`

**Comment by prokopsimek** [comment]
@ryzzaki thanks! https://github.com/Applifting/culture/commit/e379e79125d518ec3fdc13bf00838f08a4a99fbf
